/**
 * This file is part of the GATE Coreference Plugin.
 *
 * The GATE Coreference Plugin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *   
 * The GATE Coreference Plugin is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *   
 * You should have received a copy of the GNU General Public License along with the GATE
 * Coreference Plugin.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Copyright 2010 W.P. McNeill
 */

package gate.coreference.scorer;

import java.util.LinkedList;
import java.util.List;

/**
 * Precision and recall scores for a list of equivalence set pairs along with
 * their micro and macro averages. Instantiating classes should implement the
 * appropriate macro averaging scheme.
 * 
 * @author <a href="mailto:billmcn@gmail.com">W.P. McNeill</a>
 */
public abstract class PrecisionRecallAverages {
	List<PrecisionRecall> scores = new LinkedList<PrecisionRecall>();

	/**
	 * @param score
	 *            precision and recall for a pair of equivalence sets
	 */
	public void addScore(PrecisionRecall score) {
		scores.add(score);
	}

	/**
	 * @return scores for the individual equivalence set pairs
	 */
	public Iterable<PrecisionRecall> getScores() {
		return scores;
	}

	/**
	 * The micro average is the average of the precision and recall scores for
	 * the individual equivalence set pairs.
	 * 
	 * @return the micro average
	 */
	public PrecisionRecall getMicroAverage() {
		double precision = 0;
		double recall = 0;
		for (PrecisionRecall score : scores) {
			precision += score.getPrecision();
			recall += score.getRecall();
		}
		int n = scores.size();
		precision /= n;
		recall /= n;
		return new PrecisionRecall(precision, recall);
	}

	/**
	 * The macro average is the precision and recall scores generated by scoring
	 * all equivalence set pairs at once.
	 * 
	 * @return the macro average
	 */
	abstract public PrecisionRecall getMacroAverage();
}
